version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/OpenSign"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      frontend-minor-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@babel/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@mui/*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/apps/OpenSignServer"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      server-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/microfrontends/SignDocuments"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      signing-microfrontend-minor-patch:
        update-types:
          - "minor"
          - "patch"
